### ISSUE TITLE
How to support partial-upload

### ISSUE THREAD

**Issue by bonnlee2016** [FubarDevelopment/WebDavServer#63] opened 2021-09-02 09:38 UTC
hi:
    I looked at the upload logic in the source code and found that the content -range field parameter is not used. At the same time,  If you do not use offset to modify some bytes, only use copy to overwrite all file streams, It can not meet some business scenarios.

    I have tried many times and found that if I modify some bytes of a large file, the put-handle need to update the file completely, which is inefficient. 

    so  i want to kown how to support partial upload.

Thank U.

**Comment by fubar-coder** [comment] 2021-09-02 19:28
You are correct, this is not supported. I guess that it would take some effort to implement this properly and I need a client that supports it - and a way to communicate to the client that partial uploads are supported.

**Comment by fubar-coder** [comment] 2021-11-21 22:33
Duplicate of #8

**Closed as completed by fubar-coder** 2021-11-21 22:33 UTC
Labels: improvement
